### ISSUE TITLE
wro4j is not an existing directory!

### ISSUE THREAD

**Issue by wulftone** [scalatra/scalatra-website-examples#11]
Just tried to run the example and got:

```
scalatra-website-examples/2.2/resources/scalatra-coffeescript/target/wro4j is not an existing directory.
```

I made the directory, and it works... but it doesn't compile the coffeescript...

**Comment by takezoe** [comment]
Close because the wro4j example has not been maintained no longer, and dropped in Scalatra 2.6 examples.
