### ISSUE TITLE
2.3/async/scalatra-atmosphere-embedded broadcast is not broadcasting

### ISSUE THREAD

**Issue by labe-me** [scalatra/scalatra-website-examples#15]
Hi,

I was testing the two scalatra / atmosphere chat example and it looks like the broadcast() function is sending the message to none of the connected browsers. 

Best
Laurent

**Comment by labe-me** [comment]
my bad, it seems to work now… don't know what happened :)

**Comment by labe-me** [comment]
And after a refresh it's not working anymore (and it was only working for one browser).

**Comment by labe-me** [comment]
Ok, I think I had a problem with sbt and multiple containers or something like that, I restarted everything and now it doesn't fail anymore.

Sorry for the noise.

**Comment by futurechimp** [comment]
No problem, Laurent. We'd rather have a bug report about the docs than for people to stay quiet if it looks like something is incorrect.
