### ISSUE TITLE
TodosController in scalatra-commands is breaking

### ISSUE THREAD

**Issue by takezoe** [scalatra/scalatra-website-examples#32]
https://github.com/scalatra/scalatra-website-examples/blob/master/2.5/formats/scalatra-commands/src/main/scala/org/scalatra/example/databinding/TodosController.scala

Following action fails to compile.

```scala
  /* TODO broken code
  post("/todos") {
    val todo = new Todo(-1, params("name"))
    TodoData.add(TodoData.newTodo(params("name")))
    redirect("/")
  }
  */
```

**Comment by magnolia-k** [comment]
https://github.com/scalatra/scalatra-website-examples/pull/35
