### ISSUE TITLE
Swagger-example: CORS issues with swagger-ui 

### ISSUE THREAD

**Issue by martinlechner1** [scalatra/scalatra-website-examples#40]
Reproduce the problem:
- Run the swagger-example as documented
- Download and open swagger-ui as described in their documentation http://swagger.io/docs/swagger-tools/#swagger-ui-documentation-29 or use http://petstore.swagger.io/  
- Enter http://localhost:8080/api-docs/swagger.json into the input field and hit "Explore"

Expected:
- Swagger-UI shows the api

Result:
- Font gets red and dev console shows CORS errors

Explanation:
Swagger-ui uses simple get requests for the api interaction. Looking into the source of [CORSSupport](https://github.com/scalatra/scalatra/blob/2.5.x/core/src/main/scala/org/scalatra/CORSSupport.scala)
You see in `augmentSimpleRequest` in line 128 
```
request.headers.get(OriginHeader).filter(corsConfig.allowedOrigins.contains)
```
corsConfig.allowedOrigins is in our case `*`, while `request.headers.get(OriginHeader)` is in case of local swagger-ui `null` or in case of petstore `http://petstore.swagger.io`. 
Therefore the header is not added in line 130. 
This might be a bug in CORSSupport, since I would expect in case of allow * that the AccessControlAllowOriginHeader is set in any case for simple requests.

The fix for this demo project would be to add:
```scala
context.initParameters("org.scalatra.cors.allowCredentials") = "false"
```
to the init function in ScalatraBootstrap, so the condition in line 125 is true and we skip the problematic part. This approach would not be very clean though.

**Comment by takezoe** [comment]
Swagger examples have been fixed to allow to access from http://petstore.swagger.io/ in  https://github.com/scalatra/scalatra-website-examples/commit/015d5dd207ec8da2eea8704f16cfbf5e7ada5caa.
